name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REGISTRY: ${{ vars.CR_REGISTRY }}
          CR_REPOSITORY: timurguseynov
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Upload and restart the docker image
        run: |
          ssh admin@${{ vars.VM_IP_ADDRESS }} '
            sudo docker pull cr.yandex/${{ vars.CR_REGISTRY }}/timurguseynov:${{ github.sha }}
            sudo docker stop genotek_service || true &&
            sudo docker rm genotek_service || true &&
            sudo docker run -d --network host --name genotek_service -e HOST=0.0.0.0 cr.yandex/${{ vars.CR_REGISTRY }}/timurguseynov:${{ github.sha }}
          '
