name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: |
          docker build . -t genotek -f Dockerfile
          docker save genotek | gzip > genotek.tgz

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Upload and restart the docker image
        run: |
          scp genotek.tgz root@${{ vars.VM_IP_ADDRESS }}:/tmp/
          ssh root@${{ vars.VM_IP_ADDRESS }} '
            gunzip -c /tmp/genotek.tgz | docker load &&
            docker stop genotek_service || true &&
            docker rm genotek_service || true &&
            docker run -d -p 0.0.0.0:3000:3000 --name genotek_service genotek
          '

      # TODO: upload directly to VM or to registry
      #
      ## Direct upload

      #
      ## Yandex Cloud registry upload
      # - name: Login to Yandex Cloud Container Registry
      #   id: login-cr
      #   uses: yc-actions/yc-cr-login@v1
      #   with:
      #     yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
      #
      # - name: Build, tag, and push image to Yandex Cloud Container Registry
      #   run: |
      #     docker build -t cr.yandex/${{ env.YC_CR_REGISTRY }}/${{ env.YC_CR_REPOSITORY }}:$IMAGE_TAG .
      #     docker push cr.yandex/${{ env.YC_CR_REGISTRY }}/${{ env.YC_CR_REPOSITORY }}:$IMAGE_TAG
